// flow-typed signature: 640bab04fd287ce32c408886a6af2090
// flow-typed version: <<STUB>>/micro-route_v^2.4.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-route/dispatch' {
  declare module.exports: any;
}

declare module 'micro-route/match' {
  declare module.exports: any;
}

declare module 'micro-route/test/route-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-route/dispatch.js' {
  declare module.exports: $Exports<'micro-route/dispatch'>;
}
declare module 'micro-route/index' {
  declare module.exports: $Exports<'micro-route'>;
}
declare module 'micro-route/index.js' {
  declare module.exports: $Exports<'micro-route'>;
}
declare module 'micro-route/match.js' {
  declare module.exports: $Exports<'micro-route/match'>;
}
declare module 'micro-route/test/route-test.js' {
  declare module.exports: $Exports<'micro-route/test/route-test'>;
}
